### Site Settings ###
title               : josh menden
baseurl             : ""
repository          : joshmenden/me
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji

livereload: true

### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Josh Menden
  image             : assets/joshportrait.jpeg
# dribbble          : your_username
  email             : josh.menden@hey.com
# facebook          : your_username
  github            : joshmenden
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : joshmenden
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : joshmenden
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /thoughts/:title


### Collections ###
collections:
  open_source:
    output: true
    permalink: /open_source/:name
  contributions:
      output: true
      permalink: /open_source/contributions/:name
  creations:
    output: true
    permalink: /open_source/creations/:name
  books:
    output: true
    permalink: /books/:name


### Disqus ###
disqus: your-short-name-disqus                          # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "open_source"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
